# Project 3 - Bio-inspired AI
# Centralized configuration file

# Datasets to use
datasets:
  01-breast-w_lr_F.h5: 
    n_features: 8
    split: "train"
  05-credit-a_rf_F.h5:
    n_features: 15
    split: "train"
  08-letter-r_knn_F.h5:
    n_features: 16
    split: "train"
  06-zoo_lr_F.h5:
    n_features: 16
    split: "test"
  10-hepatitis_lr_F.h5:
    n_features: 19
    split: "test"
  triangle:
    n: 16
    m: 1
    s: 4
    split: "train"
  asymmetric:
    n: 31
    m: 1
    s: 5
    split: "test"

landscape:
  train_penalty: 0.1
  test_penalty: 0.0

visualization:
  neighborhood_size: 3
  output_dir: "img"

# Experiment parameters
experiment:
  n_runs: 1              # Number of independent runs
  popsize: 50             # Population size
  generations: 100        # Number of generations
  output_dir: "res"       # Base output directory

# Algorithm parameters
algorithms:
  GA:
    pc: 0.9               # Crossover probability
    pm: -1.0              # Mutation probability (-1 = auto: 1/n_bits)

  PSO:
    w: 0.7                # Inertia weight
    c1: 1.5               # Cognitive coefficient
    c2: 1.5               # Social coefficient

  NSGA2:
    pc: 0.9               # Crossover probability
    pm: -1.0              # Mutation probability (-1 = auto: 1/n_bits)



# cose da fare
# - sign up for demo day (DONE)
# - general check (expecially for GA and PSO)
# - test on synthetic landscape
# - test on test datasets
# - optional visualization (few ideas)
# - report
# - slides
